### ISSUE TITLE
>=0.6.1: Uncaught (in promise) TypeError: i.mount is not a function

### ISSUE THREAD

**Issue by esl51** [codespikex/vue3-mount#2]
Hi!

When upgrading a module from version 0.6.0 to 0.6.1-4, I get an error:

```
vue3-mount.es.js:206 Uncaught (in promise) TypeError: i.mount is not a function
    at vue3-mount.es.js:206:17
```

```js
  return !n && t && k && w("Please disable the destroy option when the hook is used outside of a setup scope."), function(f, N = "default") {
    let U = o ? n : void 0;
    const d = i.mount(f, N, U); // here
    return t && r && (d.__removeHook(() => r.delete(d.id)), r.set(d.id, d)), d;
  };
```

My code:

app.ts
```ts
// ...
import App from './App.vue'
import { createApp } from 'vue'
import Vue3Mount from 'vue3-mount'

const app = createApp(App)

// plugins
// ...
app.use(Vue3Mount)

// ...

// mount
app.mount('#app')
```

App.vue
```vue
<template>
  <transition
    name="fade"
    mode="out-in"
  >
    <app-layout />
  </transition>
  <div
    class="toast-container top-0 start-50 position-fixed p-3 translate-middle-x"
  >
    <portal name="toasts" />
  </div>
  <portal name="confirms" />
</template>

<script setup lang="ts">
import { Portal } from 'vue3-mount'
import { useToast } from './composables/useToast'

const { danger } = useToast()

danger({
  title: 'test',
  body: 'test',
})
</script>
```

useToast.ts
```ts
import OToast from '@/components/OToast.vue'
import { h } from 'vue'
import { useMount } from 'vue3-mount'

interface ToastOptions {
  variant?: string
  timeout?: number
  title?: string
  body?: string
  hint?: string
}

const toaster = () => {
  const mount = useMount()

  return (options?: ToastOptions): ReturnType<typeof mount> => {
    const unmount = () => {
      setTimeout(() => {
        mounted.unmount()
      }, 1000)
    }

    const mounted = mount(
      () =>
        h(OToast, {
          ...options,
          onHide: () => unmount(),
        }),
      'toasts'
    )

    return mounted
  }
}

export function useToast() {
  const toast = (options?: ToastOptions) => {
    return toaster()(options)
  }

  const danger = (options?: ToastOptions) => {
    const settings = options ?? ({} as ToastOptions)
    settings.variant = 'danger'
    return toaster()(settings)
  }

  const warning = (options?: ToastOptions) => {
    const settings = options ?? ({} as ToastOptions)
    settings.variant = 'warning'
    return toaster()(settings)
  }

  const info = (options?: ToastOptions) => {
    const settings = options ?? ({} as ToastOptions)
    settings.variant = 'info'
    return toaster()(settings)
  }

  const success = (options?: ToastOptions) => {
    const settings = options ?? ({} as ToastOptions)
    settings.variant = 'success'
    return toaster()(settings)
  }

  return {
    toast,
    danger,
    warning,
    info,
    success,
  }
}
```
